<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub">
      <Version>10.0.401</Version>
    </GlobalPackageReference>
    <GlobalPackageReference Include="PolySharp">
      <Version>1.16.0</Version>
    </GlobalPackageReference>
    <GlobalPackageReference Include="FredrikHr.NupkgMSBuild.GitHubPackageProjectUrlInference">
      <ProjectReference>$(MSBuildThisFileDirectory).submodules\fredrikhr\powerplatform-sdk-extensions\.submodules\fredrikhr\nuget-msbuild-extensions\build\FredrikHr.NupkgMSBuild.GitHubPackageProjectUrlInference\FredrikHr.NupkgMSBuild.GitHubPackageProjectUrlInference.csproj</ProjectReference>
      <Version>1.0.1</Version>
    </GlobalPackageReference>
  </ItemGroup>
  <ItemGroup Label="FredrikHr.NupkgMSBuild.*">
    <PackageVersion Include="FredrikHr.NupkgMSBuild.PackageAuthorSigning">
      <Version>1.1.1</Version>
    </PackageVersion>
    <PackageVersion Include="FredrikHr.NupkgMSBuild.PackPackageReference">
      <Version>1.1.1</Version>
    </PackageVersion>
    <PackageVersion Include="FredrikHr.NupkgMSBuild.StripNuspecTfm">
      <Version>1.0.0</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup Label="FredrikHr.PowerPlatformSdkExtensions.MSBuild.*">
    <PackageVersion
      Include="
        FredrikHr.PowerPlatformSdkExtensions.MSBuild.PluginPackage;
        FredrikHr.PowerPlatformSdkExtensions.MSBuild.Solution;
        "
    >
      <Version>2.11.2</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CrmSdk.CoreAssemblies">
      <Version>9.0.2.60</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup Label="Azure Core">
    <PackageVersion Include="Azure.Core">
      <Version>1.50.0</Version>
    </PackageVersion>
    <PackageVersion Include="Azure.Identity">
      <Version>1.11.4</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup Label="Azure Resource Manager">
    <PackageVersion Include="Azure.ResourceManager">
      <Version>1.13.2</Version>
    </PackageVersion>
    <PackageVersion Include="Azure.ResourceManager.Authorization">
      <Version>1.1.6</Version>
    </PackageVersion>
    <PackageVersion Include="Azure.ResourceManager.KeyVault">
      <Version>1.3.3</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup Label="Azure.Security.KeyVault.*">
    <PackageVersion
      Include="
        Azure.Security.KeyVault.Certificates;
        Azure.Security.KeyVault.Keys;
        Azure.Security.KeyVault.Secrets;
        "
      Version="4.6.0"
    />
  </ItemGroup>
  <ItemGroup Label="Microsoft Identity">
    <PackageVersion Include="Microsoft.Identity.Client">
      <Version>4.76.0</Version>
    </PackageVersion>
    <PackageVersion
      Include="
        Microsoft.IdentityModel.Protocols;
        Microsoft.IdentityModel.Protocols.OpenIdConnect;
        Microsoft.IdentityModel.Tokens;
        Microsoft.IdentityModel.JsonWebTokens;
        System.IdentityModel.Tokens.Jwt;
        "
      Version="8.14.0"
    />
  </ItemGroup>
  <ItemGroup Label="Grpc">
    <PackageVersion Include="Google.Protobuf">
      <Version>3.24.2</Version>
    </PackageVersion>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="System.ClientModel">
      <Version>1.8.0</Version>
    </PackageVersion>
    <PackageVersion Include="System.Memory">
      <Version>4.5.5</Version>
    </PackageVersion>
    <PackageVersion Include="System.Memory.Data">
      <Version>8.0.1</Version>
    </PackageVersion>
    <PackageVersion Include="System.Diagnostics.DiagnosticSource">
      <Version>7.0.2</Version>
    </PackageVersion>
  </ItemGroup>
</Project>
